# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: twakrim <taha.wakrim.pro@gmail.com>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/05 22:11:37 by twakrim           #+#    #+#              #
#    Updated: 2018/10/06 22:17:29 by twakrim          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SRCS = ft_display_file.c

all: $(NAME)

$(NAME):
	    gcc  -Wextra -Wall -Werror $(SRCS) -o $(NAME)

clean:
	    /bin/rm -f *.o

fclean: clean
	    /bin/rm -f $(name)

re: fclean all
